# Generated by Django 5.0.2 on 2024-02-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_customuser_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(blank=True),
        ),
    ]
