# Generated by Django 5.0.2 on 2024-02-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_tutor_customuser_is_student_customuser_is_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='username'),
        ),
    ]
