# Generated by Django 5.0.2 on 2024-02-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
