# Generated by Django 5.0.2 on 2024-02-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
