# Generated by Django 5.0.2 on 2024-02-26 13:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_delete_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('introduction_video', models.URLField(blank=True)),
                ('introduction_description', models.CharField(max_length=250)),
                ('teaching_style', models.CharField(max_length=100)),
                ('total_sessions', models.IntegerField()),
                ('certificates', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
