# Generated by Django 5.0.2 on 2024-02-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_tutor_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='total_sessions',
        ),
    ]
