# Generated by Django 5.0.2 on 2024-02-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_remove_tutor_total_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='certificates',
            field=models.TextField(blank=True),
        ),
    ]
