# Generated by Django 5.0.2 on 2024-02-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_tutor_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='certificates',
            field=models.URLField(blank=True),
        ),
    ]
