# Generated by Django 5.0.2 on 2024-02-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_tutor_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='certificates',
            field=models.TextField(blank=True),
        ),
    ]
