# Generated by Django 5.0.2 on 2024-03-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_customuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
