# Generated by Django 5.0.2 on 2024-03-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
