# Generated by Django 5.0.2 on 2024-05-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='dialect',
            field=models.CharField(default=False, max_length=45),
        ),
    ]
