# Generated by Django 5.0.2 on 2024-05-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_tutor_dialect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='dialect',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
