# Generated by Django 5.0.2 on 2024-05-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='student_preferences',
            field=models.CharField(default='No Preferences', max_length=200),
        ),
    ]
