# Generated by Django 5.0.2 on 2024-05-29 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_tutor_student_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='student_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
