# Generated by Django 5.0.2 on 2024-03-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='recurrence_rule',
            field=models.TextField(default=None),
        ),
    ]
