# Generated by Django 5.0.2 on 2024-03-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0002_slots_recurrence_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slots',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='recurrence_rule',
        ),
        migrations.AddField(
            model_name='slots',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
