# Generated by Django 5.0.2 on 2024-03-29 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0004_slots_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='user',
        ),
        migrations.AddField(
            model_name='slots',
            name='booked_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booked_by_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slots',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
