# Generated by Django 5.0.2 on 2024-04-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0006_remove_slots_booked_by_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
