# Generated by Django 5.0.2 on 2024-04-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0007_booking_amount_booking_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
