# Generated by Django 5.0.2 on 2024-04-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0008_alter_booking_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
