# Generated by Django 5.0.2 on 2024-05-16 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0011_alter_booking_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
